No spa
nss-evening-cohort-04/mastery-exercise-spa-ostrander-nathan pull request #1
Opened 2016-10-08 18:37 UTC by ostrander-nathan

2016-10-10 22:58 UTC, ncgonz commented
@ostrander-nathan, is this ready for review?

2016-10-11 01:29 UTC, copypastedeveloper requested changes
Most of this looks pretty good.  A couple of things to fix, and then you'll be good to go

2016-10-11 01:29 UTC, ncgonz commented on inventory.json
> +  "cars": [
Can you add more than 3 cars?  just to see the multiple rows stuff working.

2016-10-11 01:29 UTC, ncgonz commented on secondIife.js
> +	            targetToEdit = this.childNodes[4];
Using an index of a specific child node can be pretty fragile.  Imagine if someone wanted to to add another child somewhere in the carHolder element.  All of your code would now point to the wrong element.  can you think of other ways to target the element that are not as fragile?

2016-10-11 01:29 UTC, ncgonz commented on quiz.js
> +		  carsData += `<h1>${currentCar.make}</h1>`;
why are these lines tabbed so weird.  quit it.

2016-10-11 01:29 UTC, ncgonz commented on secondIife.js
> +	           	$(this).css("background-color", "#C5CADF");
Should this be in the border class?

2016-10-11 15:07 UTC, ostrander-nathan commented on quiz.js
> +		  carsData += `<h1>${currentCar.make}</h1>`;
fixed

2016-10-11 15:07 UTC, ostrander-nathan commented on secondIife.js
> +	           	$(this).css("background-color", "#C5CADF");
not sure what you mean on this one

2016-10-11 15:07 UTC, ostrander-nathan commented on inventory.json
> +  "cars": [
Added 3 cars to show rows

2016-10-11 15:09 UTC, ostrander-nathan commented on secondIife.js
> +	            targetToEdit = this.childNodes[4];
I am guessing I would need to select the description by name instead of node position but not exactly sure how to execute that

2016-10-15 14:23 UTC, ncgonz commented on secondIife.js
> +	           	$(this).css("background-color", "#C5CADF");
@ostrander-nathan was just curious why you added a class to the div, and then manually changed the background color.  It works, so you don't **need** to _fix_ it, just something to think about.

2016-10-15 14:24 UTC, copypastedeveloper approved these changes

2016-10-15 14:24 UTC, ncgonz commented
looks good. 👍

2016-10-15 16:25 UTC, merged